name: Deploy Rohit Portfolio Angular Web App to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch: 
  
defaults:
  run:
    working-directory: my-portfolio-angular/portfolio-site

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Prerender Angular app
        run: npx ng run portfolio-site:prerender --configuration production --base-href "/my-portfolio-angular/"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: my-portfolio-angular/portfolio-site/dist/portfolio-site/browser
